plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tuff.browser'
    compileSdk 35

    defaultConfig {
        applicationId "com.tuff.browser"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0.0"

        vectorDrawables.useSupportLibrary = true
        resourceConfigurations += ['en']
    }

    signingConfigs {
        release {
            storeFile file('release.jks')
            storePassword 'tuffpass'
            keyAlias 'tuff'
            keyPassword 'tuffpass'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
